server:
  port: 8085
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@${MONGO_HOST:localhost}:27017/fluxbank?authSource=admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
