services:

  # Infrastructure
  postgres:
    image: postgres:latest
    container_name: fluxbank-postgres
    restart: unless-stopped
    ports: 
    - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fluxbank
    volumes:
      - fluxbank_postgres_data:/var/lib/postgresql/data
    #networks:
    # - fluxbank-database-network
  redis:
    image: redis:latest
    container_name: fluxbank-redis
    restart: unless-stopped
    ports:
    - 6379:6379
    #networks:
    # - fluxbank-cache-network
  #mongodb:
  #  image: mongo:latest
  #  container_name: fluxbank-mongo
  #  restart: unless-stopped
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: root
  #  ports:
  #    - 27017:27017
  #  volumes:
  #    - fluxbank_mongo_data:/var/lib/mongo/data
  #  #networks:
  #  # - fluxbank-database-network
#
  #zookeeper:
  #  image: confluentinc/cp-zookeeper:latest
  #  container_name: fluxbank-zookeeper
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #    ZOOKEEPER_TICK_TIME: 2000
  #  ports:
  #    - 2181:2181
  #  #networks:
  #  #  - fluxbank-message-network
#
  #kafka:
  #  image: confluentinc/cp-kafka:latest
  #  container_name: fluxbank-kafka
  #  depends_on:
  #    - zookeeper
  #  ports:
  #    - 9092:9092
  #  environment:
  #    KAFKA_BROKER_ID: 1
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
  #    KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092 # kafka:9092
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
  #    KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #  #networks:
  #  # - fluxbank-message-network
#
  ## Monitoring
  #prometheus:
  #  image: prom/prometheus:latest
  #  container_name: fluxbank-prometheus
  #  restart: unless-stopped
  #  volumes:
  #    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #    - ./prometheus/prometheus_data:/prometheus
  #  command:
  #    - '--config.file=/etc/prometheus/prometheus.yml'
  #    - '--storage.tsdb.path=/prometheus'
  #    - '--web.console.libraries=/etc/prometheus/console_libraries'
  #    - '--web.console.templates=/etc/prometheus/consoles'
  #    - '--web.enable-lifecycle'
  #  ports:
  #    - 9090:9090
  #  #networks:
  #  #  - fluxbank-monit-network
  #  user: root
#
  #grafana:
  #  image: grafana/grafana
  #  container_name: fluxbank-grafana
  #  volumes:
  #    - fluxbank_grafana_data:/var/lib/grafana
  #  restart: unless-stopped
  #  ports:
  #    - 3000:3000
  #  #networks:
  #  #  - fluxbank-monit-network
  #  depends_on:
  #    - prometheus
  #  user: root

networks:
  fluxbank-monit-network:
    internal: true
    name: fluxbank-monit-network
  fluxbank-message-network:
    internal: true
    name: fluxbank-message-network
  fluxbank-cache-network:
    internal: true
    name: fluxbank-cache-network
  fluxbank-database-network:
    internal: true
    name: fluxbank-database-network
  
volumes:
  fluxbank_postgres_data:
  fluxbank_mongo_data:
  fluxbank_grafana_data: