server:
  port: 8083
spring:
  application:
    name: transaction-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: fluxbank
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:root}
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: jdbc:postgresql://${TRANSACTION_POSTGRES_HOST:localhost}:5434/${POSTGRES_DB:fluxbank}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: transaction-service
