logging:
  level:
    org:
      springframework:
        transaction: TRACE
      hibernate:
        SQL: DEBUG
server:
  port: 8081
spring:
  application:
    name: wallet-service
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:fluxbank?createDatabaseIfNotExist=true}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
