server:
  port: 8080
spring:
  application:
  name: gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: wallet-service
gateway:
  routes:
    wallet-service: ${WALLET_SERVICE_URI:http://localhost:8081}
    user-service: ${USER_SERVICE_URI:http://localhost:8082}
    transaction-service: ${TRANSACTION_SERVICE_URI:http://localhost:8083}
