server:
  port: 8080
spring:
  application:
  name: gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    enable:
      jvm: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: gateway-service
gateway:
  routes:
    wallet-service: ${WALLET_SERVICE_URI:http://localhost:8081}
    user-service: ${USER_SERVICE_URI:http://localhost:8082}
