server:
  port: 8080
spring:
  application:
  name: gateway-service
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: gateway-service