server:
  port: 8084

spring:
  application:
    name: fraud-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/fluxbank?authSource=admin
aws:
  sns:
    fraud-check-completed-topic: arn:aws:sns:us-east-1:710271919573:fraud-check-completed
  lambda:
    fraud-detection: fraud-dev-lambda
