server:
  port: 8084

spring:
  application:
    name: fraud-service
  data:
    mongodb:
      uri: mongodb://root:root@${MONGO_HOST:localhost}:27017/fluxbank?authSource=admin
aws:
  sns:
    fraud-check-completed-topic: ${FRAUD_CHECK_COMPLETED_ARN}
  lambda:
    fraud-detection: ${FRAUD_DETECTION_LAMBDA:fraud-dev-lambda}
  region: ${AWS_REGION:us-east-1}
