name: CI - Testes e SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-and-analyse:
    runs-on: ubuntu-lastest
    strategy:
      matrix: 
        service:
          - wallet-service
          - user-service 
          - transaction-service
    steps:

      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run unit tests 
        working-directory: ${{ matrix.service }}
        run: mvn test

      
