name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build projeto
        run: mvn clean install -DskipTests
    
      - name: Analyze with SonarCloud
      
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args:
            -Dsonar.projectKey=l-furquim_flux-bank
            -Dsonar.organization=l-furquim
            -Dsonar.sources=fraud-service,user-service,transaction-service,wallet-service,gateway-service

