name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build fraud-service
        working-directory: fraud-service
        run: mvn clean install -DskipTests

      - name: Build user-service
        working-directory: user-service
        run: mvn clean install -DskipTests

      - name: Build transaction-service
        working-directory: transaction-service
        run: mvn clean install -DskipTests

      - name: Build wallet-service
        working-directory: wallet-service
        run: mvn clean install -DskipTests

      - name: Build gateway-service
        working-directory: gateway-service
        run: mvn clean install -DskipTests

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=l-furquim_flux-bank
            -Dsonar.organization=l-furquim
            -Dsonar.sources=fraud-service,user-service,transaction-service,wallet-service,gateway-service
            -Dsonar.java.binaries=\
              fraud-service/target/classes,\
              user-service/target/classes,\
              transaction-service/target/classes,\
              wallet-service/target/classes,\
              gateway-service/target/classes
